### PR TITLE
Box2d Plugin - Added static bodies support.

### PR DESCRIPTION
**Pull request by 133794m3r**
Since box2d support is in here. For things like the ground/walls there should be support for static bodies. This patch does just that. One line change really.

### CODE REVIEW

**Comment by karai17** [comment]
Should the code path for static data also be creating a new body that is flagged as dynamic, or should that be flagged as something else?

**Comment by 133794m3r** [comment]
In box2d I believe bodies can only be kinematic, dynamic, or static. That's why I made it and elseif. For all 3 types I don't believe they can be both for the object.

**Comment by karai17** [comment]
Right, but what I am saying is that in your PR, both static and dynamic userdata objects are being turned into dynamic bodies. Was that intentional, or is the new line of code supposed to be static?

**Comment by 133794m3r** [comment]
Woops, I forgot to change the property after copy-pasting that line of code. it isn't supposed to be like that. I literally just copy-pasted it so that it followed the same style. Sorry I didn't catch on before. I'll modify the code to work properly on that branch.

**Comment by 133794m3r** [comment]
I'm dumb and instead of having 3 commits to do what should've been a single one it's now in #240 it's 2 commits b/c I forgot to include comments about the new body types but I _think_ the thing is fixed now.

**Pull request closed without merging**
