### PR TITLE
Submodule support

### PR DESCRIPTION
**Pull request by buckle2000**

### CODE REVIEW

**Comment by karai17** [comment]
The vscode folder is there for a reason, and I don't really like your path change. Sorry.

**Comment by buckle2000** [comment]
Why?
What if somebody does this:
`require('sti/init')`
then the `gsub('%.init')` thing will not work.

**Comment by VideahGams** [comment]
@karai17 What's the reason for the vscode folder being there? Why not stick it in .gitignore?

**Comment by karai17** [comment]
@buckle2000 Why would someone require sti/init? That's not how Lua works.

@VideahGams Because the sti repo is not just the module, it also includes a code example so having a build file can make sense.

**Comment by buckle2000** [comment]
@karai17 there will be.

**Comment by karai17** [comment]
There will be what?

**Comment by buckle2000** [comment]
There will be people `require('sti/init')`.

**Comment by karai17** [comment]
It's not up to sti to work around people's incorrect code. That line is incorrect in several different ways. Using sti requires that you understand Lua and LOVE to some degree.

**Comment by buckle2000** [comment]
How is `require('sti/init')` "incorrect"?

**Comment by karai17** [comment]
Require is not supposed to use slashes since the argument is not a
filesystem path, it is a module. Slash just so happens to work on some
platforms but it is not officially supported.

Lua modules expect an init.lua file, so directly accessing it is not
necessary or recommended.

**Comment by buckle2000** [comment]
This is just something like PEP8, recommended but not required.

**Comment by karai17** [comment]
In this case, it is neither recommended nor required.

**Comment by buckle2000** [comment]
Well, up to you.

**Comment by shakesoda** [comment]
Using slashes in Lua require paths is **outright wrong**. It breaks caching, is inconsistent with native modules and totally ignores how search paths work.

It's not wrong because of preference or style. It's wrong because it breaks the module system.

@karai17 the repo probably should *just* be the module, not the other stuff. Just make a demo repo or something.

**Pull request closed without merging**
