### PR TITLE
basic support for object layers in bump plugin

### PR DESCRIPTION
**Pull request by premek**

### CODE REVIEW

**Comment by Bobbyjoness** [comment]
I just test and it doesn't work for me. Do you have a test .love with the map.tmx that I can use? Also you only do collision for the layer.

**Comment by premek** [comment]
@Bobbyjoness you're right I only added support for what I needed -- only when the whole layer has property "collidable", not individual objects. And rectangle shapes and tile objects only.

**Comment by premek** [comment]
attached is minimal working example
[sti-bump-test.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/76691/sti-bump-test.zip)

**Comment by premek** [comment]
I added support for individual objects in a layer that does not have "collidable" property
[sti-bump-test.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/76704/sti-bump-test.zip)

**Comment by Bobbyjoness** [comment]
@karai17 @premek  I tested and it works.

**Comment by karai17** [comment]
If you can fix the merge conflict, I will accept this PR.

**Comment by premek** [comment]
fixed

**Comment by karai17** [comment]
Woooo!

**Pull request merged**
